### ISSUE TITLE
Provide counsel-dash-at-point

### ISSUE THREAD

**Issue by thblt** [nathankot/counsel-dash#3]
`helm-dash-at-point` does the same as helm-dash, but prefills the search field with the symbol at point.  This is extremely useful to quickly look up whatever it is you're working on.

Thanks :-)

**Comment by nathankot** [comment]
This should be really easy to implement, something like:

``` elisp
(defun counsel-dash-at-point ()
  (interactive)
  (counsel-dash (thing-at-point 'symbol)))
```

Feel free to send a PR in ;)

**Comment by gilbertw1** [comment]
This function was added during the backend migration to `dash-docs`.
