### ISSUE TITLE
Use new `dash-docs` package instead of `helm-dash`

### ISSUE THREAD

**Issue by gilbertw1** [nathankot/counsel-dash#7]
Hi, I've been working on splitting out the dash specific logic from `helm-dash` into it's own package `dash-docs` that doesn't have any dependency on helm. The package has been submitted to MELPA and `helm-dash will soon be updated to use it underneath. 

You can find details on the transition in this issue: areina/helm-dash#173

I just wanted to give you a heads up on this. The transition in helm-dash will not break counsel-dash and I've already made the changes to use `dash-docs` in a fork. Once `dash-docs` has been included in MELPA I'll submit a PR including the changes necessary to use `dash-docs` and no longer depend on `helm-dash`.

Thanks!

**Comment by jsmestad** [comment]
@gilbertw1 happy to help test or lend a hand 😃

**Comment by gilbertw1** [comment]
Alright, `dash-docs` has been submitted to melpa and `helm-dash` has been updated to depend on the `dash-docs` package internally. I've submitted a Pull Request that adds support to base this package off of `dash-docs` which will remove the dependency on helm.

Additionally, and this is optional. Please consider moving this repository to the `dash-docs-el` organization. This is an attempt to unify these three projects under a dash specific organization so that they can be co-located and evolve together.

Thanks!

**Comment by nathankot** [comment]
Hey @gilbertw1 just catching up on this!

>  Please consider moving this repository to the dash-docs-el organization.

Happy to do this, mind if I transfer ownership of this repo to you so you can put in in that organization? 

Edit: looks like you'll need to remove or rename gilbertw1/counsel-dash before I can transfer this to you, otherwise if you give me create repository permissions on that org I can transfer it over there.

**Comment by gilbertw1** [comment]
@nathankot Sounds great, I just sent you an invitation.

Thanks!

**Comment by nathankot** [comment]
@gilbertw1 done!

**Comment by gilbertw1** [comment]
@nathankot Thanks! I've merged the changes and everything looks good ... no more helm dependency! :)
